### ISSUE TITLE
Gem is not published on RubyGems.org

### ISSUE THREAD

**Issue by aambupe** [bbc/lava-frame_compare#1]
lava-frame_compare gem does not appear to have published on RubyGems yet.

`mc-s083400:avqm ambupa01$ gem install lava-frame_compare`
`ERROR:  Could not find a valid gem 'lava-frame_compare' (>= 0) in any repository
ERROR:  Possible alternatives: secure_compare, securecompare, vagrant-compose, web_image_compare`

**Comment by davidbuckhurst** [comment]
Done
